export enum ErrorCodes {
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
    DNI_ALREADY_REGISTERED = 'DNI_ALREADY_REGISTERED',
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    SERVER_ERROR = 'SERVER_ERROR',
    ALREADY_VINCULATED_STORE = 'ALREADY_VINCULATED_STORE',
    INVALID_DATE = 'INVALID_DATE',
    PACKAGE_NOT_FOUND = 'PACKAGE_NOT_FOUND',
    INVALID_DATA = 'INVALID_DATA',
    CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND'
}